### ISSUE TITLE
[Playwright] released package has wrong dependencies (configuration plugin)

### ISSUE THREAD

**Issue by le-yams** [SpecFlowOSS/SpecFlow.Actions#71] opened 2022-02-04 15:34 UTC
Hello,

[SpecFlow.Actions.Playwright](https://www.nuget.org/packages/SpecFlow.Actions.Playwright) 0.1.258 was released a few hours ago but its dependencies seems to be wrong regarding the specflow configuration plugin.

It seems that it points to the same version:
> [SpecFlow.Actions.Configuration.SpecFlowPlugin](https://www.nuget.org/packages/SpecFlow.Actions.Configuration.SpecFlowPlugin/) (>= 0.1.258)

but this one does not exist. [SpecFlow.Actions.Configuration.SpecFlowPlugin](https://www.nuget.org/packages/SpecFlow.Actions.Configuration.SpecFlowPlugin/) latest is 0.1.250 (and is also marked as deprecated).

Here is the error I get when trying to install SpecFlow.Actions.Playwright 0.1.258:
> Unable to find package SpecFlow.Actions.Configuration.SpecFlowPlugin with version (>= 0.1.258)
>  - Found 1 version(s) in nuget.org [ Nearest version: 0.1.250 ]

Thank you in advance :)

Regards,
Yann

**Comment by CyborTronik** [comment] 2022-02-06 23:45
Same issue on ubuntu

**Comment by andrewmk** [comment] 2022-02-14 11:30
Same here - I'm stuck using SpecFlow.Actions.Playwright version 0.1.178 and can't upgrade to 0.1.258 because of the wrong dependency.

**Comment by SabotageAndi** [comment] 2022-03-08 13:20
fixed with #74 - upload to NuGet.org is done within the hour

**Comment by andrewmk** [comment] 2022-03-08 15:32
I can confirm that I've successfully updated SpecFlow.Actions.Playwright to 0.1.258 and everything seems to work as it should. Thanks.

**Comment by SabotageAndi** [comment] 2022-03-09 09:11
@le-yams I can't reproduce your issue. 
I added a new example project for Playwright (https://github.com/SpecFlowOSS/SpecFlow-Examples/tree/master/Actions/PlaywrightExample) and this is working.

Please open a new issue. Looks like it is something different,

**Closed by SabotageAndi** 2022-03-09 09:11 UTC
